"""drop_file_first_tables

Revision ID: 386812174df4
Revises: dd7f4097d9e8
Create Date: 2026-06-02 02:24:20.867805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386812174df4'
down_revision: Union[str, Sequence[str], None] = 'dd7f4097d9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('ocr_logs')
    op.drop_table('claims')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('claim_text', sa.VARCHAR(), nullable=False),
    sa.Column('metrics', sa.VARCHAR(), nullable=True),
    sa.Column('evidence', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('replicated', sa.BOOLEAN(), nullable=False),
    sa.Column('replication_error', sa.VARCHAR(), nullable=True),
    sa.Column('user_instructions', sa.VARCHAR(), nullable=True),
    sa.Column('user_screenshots', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=False),
    sa.Column('char_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
