"""add_opencode_fields

Revision ID: 9ecdec9a508f
Revises: 82dc2f2f8180
Create Date: 2026-06-01 16:07:51.044686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecdec9a508f'
down_revision: Union[str, Sequence[str], None] = '82dc2f2f8180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('opencode_session_id', sa.String(length=200), nullable=True))
    op.add_column('jobs', sa.Column('opencode_server_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'opencode_server_url')
    op.drop_column('jobs', 'opencode_session_id')
    # ### end Alembic commands ###
